# Generated by Django 5.2.8 on 2025-11-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_birthday_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clan_tag',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
